services:
  warproxy:
    image: ghcr.io/kingcc/warproxy:latest
    restart: always
    environment:
      - WARP_PLUS=true
      - ENDPOINT=162.159.192.12
      - DNS=223.5.5.5
      - HTTP_PORT=1081
    ports:
      - 1080:1080
      - 1081:1081